version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-vnalgo
    environment:
      POSTGRES_DB: vnalgo
      POSTGRES_USER: vnalgo
      POSTGRES_PASSWORD: vnalgo123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vnalgo"]
      interval: 30s
      timeout: 10s
      retries: 3

  minio:
    image: minio/minio:latest
    container_name: minio-vnalgo
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-vnalgo
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
    volumes:
      - grafana-data:/var/lib/grafana
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  jupyter:
    image: jupyter/datascience-notebook:latest
    container_name: jupyter-vnalgo
    ports:
      - "8888:8888"
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "vnalgo123"
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks
      - ./data:/home/jovyan/work/data
      - ./src:/home/jovyan/work/src
    command: start-notebook.sh --NotebookApp.token='vnalgo123' --NotebookApp.password='' --NotebookApp.allow_root=True

volumes:
  postgres-data:
  minio-data:
  grafana-data: