# Kafka Configuration for Vietnamese Market Data Streaming

kafka:
  bootstrap_servers:
    - "localhost:9092"
  
  # Producer Configuration
  producer:
    client_id: "vn-algo-producer"
    acks: "all"  # Wait for all replicas
    retries: 3
    batch_size: 16384  # 16KB
    linger_ms: 10  # Wait up to 10ms to batch records
    buffer_memory: 33554432  # 32MB
    compression_type: "snappy"
    max_request_size: 1048576  # 1MB
    enable_idempotence: true
    
    # Performance tuning
    batch_size_boost_factor: 2
    max_in_flight_requests_per_connection: 5
    request_timeout_ms: 30000
    delivery_timeout_ms: 120000
  
  # Consumer Configuration
  consumer:
    group_id: "vn-algo-consumers"
    client_id: "vn-algo-consumer"
    auto_offset_reset: "latest"
    enable_auto_commit: true
    auto_commit_interval_ms: 5000
    max_poll_records: 500
    max_poll_interval_ms: 300000  # 5 minutes
    session_timeout_ms: 10000
    heartbeat_interval_ms: 3000
    fetch_min_bytes: 1
    fetch_max_wait_ms: 500
    
    # Error handling
    max_retries: 3
    retry_backoff_ms: 1000
    reconnect_backoff_ms: 50
    reconnect_backoff_max_ms: 1000

# Topic Configuration
topics:
  market_ticks:
    name: "vn-market-ticks"
    partitions: 12  # Distribute load across multiple partitions
    replication_factor: 3
    config:
      cleanup_policy: "delete"
      retention_ms: 259200000  # 3 days
      segment_ms: 86400000  # 1 day
      compression_type: "snappy"
      min_insync_replicas: 2
    description: "Real-time tick data from Vietnamese market sources"
  
  market_bars:
    name: "vn-market-bars"
    partitions: 6
    replication_factor: 3
    config:
      cleanup_policy: "delete"
      retention_ms: 604800000  # 7 days
      segment_ms: 86400000  # 1 day
      compression_type: "snappy"
      min_insync_replicas: 2
    description: "OHLCV bar data aggregated from ticks"
  
  market_indices:
    name: "vn-market-indices"
    partitions: 3
    replication_factor: 3
    config:
      cleanup_policy: "delete"
      retention_ms: 2592000000  # 30 days
      segment_ms: 86400000  # 1 day
      compression_type: "snappy"
      min_insync_replicas: 2
    description: "Vietnamese market indices (VN-Index, VN30, etc.)"
  
  trading_signals:
    name: "vn-trading-signals"
    partitions: 6
    replication_factor: 3
    config:
      cleanup_policy: "delete"
      retention_ms: 604800000  # 7 days
      segment_ms: 86400000  # 1 day
      compression_type: "snappy"
      min_insync_replicas: 2
    description: "Trading signals generated by strategies"
  
  risk_events:
    name: "vn-risk-events"
    partitions: 3
    replication_factor: 3
    config:
      cleanup_policy: "delete"
      retention_ms: 2592000000  # 30 days
      segment_ms: 86400000  # 1 day
      compression_type: "snappy"
      min_insync_replicas: 2
    description: "Risk management events and alerts"

# Schema Registry Configuration
schema_registry:
  url: "http://localhost:8081"
  compatibility_level: "BACKWARD"  # Allow removing fields
  
  subjects:
    market_data: "vn-market-ticks-value"
    trading_signals: "vn-trading-signals-value"
    risk_events: "vn-risk-events-value"

# Streaming Configuration
streaming:
  checkpoint_location: "./checkpoints"
  trigger_interval: "10 seconds"
  watermark_delay: "2 minutes"
  
  # Delta Lake paths
  data_paths:
    bronze: "./data/delta/bronze"
    silver: "./data/delta/silver"
    gold: "./data/delta/gold"
  
  # Processing windows
  windows:
    bars_1m: "1 minute"
    bars_5m: "5 minutes"
    bars_15m: "15 minutes"
    bars_1h: "1 hour"
    daily_summary: "1 day"
  
  # Performance tuning
  spark_config:
    spark.sql.adaptive.enabled: "true"
    spark.sql.adaptive.coalescePartitions.enabled: "true"
    spark.sql.streaming.checkpointLocation: "./checkpoints"
    spark.sql.extensions: "io.delta.sql.DeltaSparkSessionExtension"
    spark.sql.catalog.spark_catalog: "org.apache.spark.sql.delta.catalog.DeltaCatalog"
    spark.serializer: "org.apache.spark.serializer.KryoSerializer"
    spark.sql.streaming.metricsEnabled: "true"

# Monitoring Configuration
monitoring:
  metrics:
    enabled: true
    interval_seconds: 30
    
  jmx:
    enabled: true
    port: 9999
    
  health_check:
    interval_seconds: 60
    timeout_seconds: 10
    
  alerts:
    lag_threshold_ms: 10000  # Alert if consumer lag > 10s
    error_rate_threshold: 0.05  # Alert if error rate > 5%
    throughput_threshold: 100  # Alert if throughput < 100 msg/s

# Vietnamese Market Specific Configuration
vietnamese_market:
  timezone: "Asia/Ho_Chi_Minh"
  currency: "VND"
  
  # Trading sessions
  trading_hours:
    morning:
      start: "09:00"
      end: "11:30"
    afternoon:
      start: "13:00"
      end: "15:00"
  
  # Market data sources
  data_sources:
    priority_order:
      - "SSI"        # Real-time WebSocket
      - "VNDirect"   # Reliable historical
      - "TCBS"       # Backup source
  
  # Symbol validation
  symbols:
    pattern: "^[A-Z]{3,4}$"
    vn30_stocks:
      - "VIC"  # Vingroup
      - "VNM"  # Vietnam Dairy
      - "HPG"  # Hoa Phat Group
      - "VCB"  # Vietcombank
      - "FPT"  # FPT Corporation
      - "GAS"  # PetroVietnam Gas
      - "BID"  # BIDV
      - "CTG"  # VietinBank
      - "MSN"  # Masan Group
      - "PLX"  # Petrolimex
  
  # Data quality thresholds
  quality_thresholds:
    price_change_limit: 0.07  # ±7% daily limit
    volume_spike_threshold: 5.0  # 5x average volume
    missing_data_threshold: 0.02  # Max 2% missing data
    latency_threshold_ms: 5000  # Max 5s latency

# Development and Testing
development:
  mock_data:
    enabled: true
    symbols: ["VIC", "VNM", "HPG", "VCB", "FPT"]
    days: 30
    tick_interval_ms: 1000  # Generate tick every second
  
  test_topics:
    prefix: "test-"
    auto_delete: true
    retention_ms: 3600000  # 1 hour for test data
  
  debug:
    console_output: true
    log_level: "INFO"
    sample_rate: 0.1  # Log 10% of messages for debugging

# Security Configuration (for production)
security:
  ssl:
    enabled: false
    keystore_location: ""
    keystore_password: ""
    truststore_location: ""
    truststore_password: ""
  
  sasl:
    enabled: false
    mechanism: "PLAIN"
    username: ""
    password: ""
  
  acl:
    enabled: false
    principal: "User:vn-algo-trading"

# Disaster Recovery
disaster_recovery:
  backup:
    enabled: true
    s3_bucket: "vn-algo-backup"
    retention_days: 90
  
  replication:
    enabled: false
    target_cluster: ""
    topics_whitelist: "vn-.*"
  
  monitoring:
    cross_cluster_lag_threshold_ms: 30000